version: '3.4'

services:
  homeassistant.mqtt:
    image: ${DOCKER_REGISTRY-}homeassistantmqtt
    restart: always
    build:
      context: .
      dockerfile: HomeAssistant.MQTT/Dockerfile
    ports:
      - "1883:1883"

  homeassistant.api:
    image: ${DOCKER_REGISTRY-}homeassistantapi
    restart: always
    build:
      context: .
      dockerfile: HomeAssistant.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://homeassistant.mongodb:27017/
    depends_on:
      - homeassistant.mongodb

  homeassistant.mongodb:
    image: mongo:7.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - database:/data/db
volumes:
  database: